### ISSUE TITLE
テキスト入力画面でリロードするとエラーが出る

### ISSUE THREAD

**Issue by e-mizutani** [chashi332/carddx#10]
GETで表示（リロード）する時にトップへ戻すルーティングに設定したい

**Comment by e-mizutani** [comment]
routerへGET時にトップに戻すように設定したが改善せず

**Comment by e-mizutani** [comment]
Gemfileから「gem 'turbolinks', '~> 5'」を削除
app/assets/javascripts/application.jsから「//= require turbolinks」を削除
bundle updateとbundle cleanを実行し改善。
動作の確認をお願いします。

**Comment by e-mizutani** [comment]
上記修正により装飾が無効になったため、切り戻ししました。
再度、模索します。

**Comment by green-peas** [comment]
JS修正しました。
リロード時にも問題なし。
