### ISSUE TITLE
他の人に送信時のユーザー検索が動作しない

### ISSUE THREAD

**Issue by green-peas** [chashi332/carddx#3]
カード送信→他の人におくる→検索を行ったときに、動作しない。
どうにかしてカード情報受け渡しが必要。

**Comment by jinbee** [comment]
ransack使用時のメソッドをPostにして引き継ぐよう修正

**Comment by green-peas** [comment]
検索は動作しましたが、
結果が０件の場合の戻るに問題があります。別イシューで上げました。
